from fpdf import FPDF
name = input('Name: ')
pdf = FPDF(orientation='portrait', format='A4')
pdf.add_page()
pdf.set_font('Helvetica', 'B', 50)
pdf.cell(0, 60, txt = 'CS50 Shirtificate', new_x='LMARGIN', new_y='NEXT', align='C')
pdf.image('shirtificate.png', w = pdf.epw)
pdf.set_font_size(30)
pdf.set_text_color(255,255,255)
pdf.text(x=47.5, y=140, txt=f'{name} took CS50')
pdf.output('shirtificate.pdf')
